const $ = (selector, root = document) => root.querySelector(selector);
const page = document.body.dataset.page || '';
let todoInstallPrompt = null;
const store = {
  get(key, fallback = null) { try { return JSON.parse(localStorage.getItem(`todo_${key}`)) ?? fallback; } catch { return fallback; } },
  set(key, value) { localStorage.setItem(`todo_${key}`, JSON.stringify(value)); }
};

const services = [
  { id:'chat', icon:'💬', title:'AI Chat', desc:'Hindi ya English mein kisi bhi topic par smart answers.', info:'TODO AI aapke sawaalon, planning, explanations aur daily tasks mein madad karta hai.' },
  { id:'write', icon:'✍️', title:'Writing Assistant', desc:'Emails, captions aur professional content likhein.', info:'Apna topic aur tone batayein. TODO AI aapke liye clear, polished content taiyar karega.' },
  { id:'study', icon:'📚', title:'Study Helper', desc:'Mushkil topics ko aasaan bhaasha mein samjhein.', info:'Concept explanations, revision plans aur practice questions ke saath behtar padhaai karein.' },
  { id:'ideas', icon:'💡', title:'Idea Generator', desc:'Business, content aur projects ke creative ideas.', info:'Naye business, video, project ya social content ke liye useful ideas generate karein.' },
  { id:'translate', icon:'🌐', title:'Smart Translator', desc:'Hindi aur English content ko naturally translate karein.', info:'Meaning aur tone preserve karke natural language translation paayein.' },
  { id:'resume', icon:'🧾', title:'Resume Builder', desc:'Professional resume content aur improvements.', info:'Role ke hisaab se impactful summary, skills aur experience bullets banayein.' },
  { id:'voice', icon:'🎙️', title:'Voice Assistant', desc:'AI se natural voice conversation.', info:'Voice Assistant abhi development mein hai.', coming:true },
  { id:'image', icon:'🖼️', title:'AI Image Studio', desc:'Creative images aur designs generate karein.', info:'AI Image Studio jaldi available hoga.', coming:true }
];
const notices = [
  {id:1,title:'Welcome to TODO AI',date:'7 July 2026',text:'Aapka smart AI workspace taiyar hai. Sabhi tools explore karein.',unread:true},
  {id:2,title:'New Writing Assistant',date:'6 July 2026',text:'Ab professional emails aur captions seconds mein likhein.',unread:true},
  {id:3,title:'Privacy reminder',date:'5 July 2026',text:'Passwords aur banking information AI chat mein share na karein.',unread:false}
];

applyTheme();
if ('serviceWorker' in navigator && location.protocol.startsWith('http')) window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();todoInstallPrompt=event;updateInstallButtons()});
window.addEventListener('appinstalled',()=>{todoInstallPrompt=null;store.set('installed',true);showToast('TODO AI installed successfully');updateInstallButtons()});
if (page === 'splash') initSplash();
else if (page === 'login') initLogin();
else if (page === 'signup') initSignup();
else {
  initAppPage();
}

function isProtected(name){ return ['home','services','service-detail','notifications','profile','settings','help','search'].includes(name); }
function initSplash(){
  location.replace('service-detail.html?id=chat');
}
function initLogin(){
  setupPasswordToggle();
  $('#loginForm').addEventListener('submit',e=>{
    e.preventDefault(); clearErrors(); const id=$('#identity').value.trim(), pass=$('#password').value;
    let ok=true; if(!validIdentity(id)){setError('identity','Valid email ya 10-digit phone likhein');ok=false} if(pass.length<6){setError('password','Password minimum 6 characters hona chahiye');ok=false}
    if(!ok)return; const btn=$('#loginBtn'); loading(btn,true,'Logging in...');
    setTimeout(()=>{ const saved=store.get('account'); store.set('user',saved || {name:'TODO User',email:id,phone:''}); location.href='home.html'; },700);
  });
  $('#forgot').onclick=()=>showToast('Password reset link demo mode mein available nahi hai.');
}
function initSignup(){
  setupPasswordToggle();
  $('#signupForm').addEventListener('submit',e=>{
    e.preventDefault(); clearErrors(); const name=$('#name').value.trim(),id=$('#identity').value.trim(),pass=$('#password').value,confirm=$('#confirm').value; let ok=true;
    if(name.length<2){setError('name','Full name likhein');ok=false} if(!validIdentity(id)){setError('identity','Valid email ya 10-digit phone likhein');ok=false} if(pass.length<6){setError('password','Minimum 6 characters');ok=false} if(pass!==confirm){setError('confirm','Passwords match nahi karte');ok=false}
    if(!ok)return; loading($('#signupBtn'),true,'Creating...'); const account={name,email:id.includes('@')?id:'',phone:id.includes('@')?'':id};
    setTimeout(()=>{store.set('account',account);store.set('user',account);location.href='home.html'},700);
  });
}
function setupPasswordToggle(){ document.querySelectorAll('[data-toggle-password]').forEach(btn=>btn.onclick=()=>{const input=$(`#${btn.dataset.togglePassword}`);input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'Show':'Hide'}); }
function validIdentity(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)||/^\d{10}$/.test(value)}
function setError(id,msg){$(`[data-error=${id}]`).textContent=msg} function clearErrors(){document.querySelectorAll('.error').forEach(x=>x.textContent='')}

function initAppPage(){
  renderShell();
  const renderers={home:renderHome,services:renderServices,'service-detail':renderDetail,notifications:renderNotifications,profile:renderProfile,settings:renderSettings,help:renderHelp,about:renderAbout,privacy:()=>renderPolicy('privacy'),terms:()=>renderPolicy('terms'),search:renderSearch,'404':render404};
  (renderers[page]||render404)();
  window.addEventListener('online',()=>showToast('Internet connection wapas aa gaya.'));
  window.addEventListener('offline',()=>showToast('No Internet Connection'));
}
function renderShell(){
  if(!$('#shell'))return; const user=store.get('user',{name:'Guest'}); const initials=user.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
  $('#shell').innerHTML=`<header class="topbar"><a class="logo" href="home.html"><span class="logo-mark">T</span><span>TODO <em>AI</em><small>Think. Ask. Create.</small></span></a><div class="top-actions"><button class="icon-btn install-app-action" type="button" aria-label="Install TODO AI">⇩</button><a class="icon-btn" href="search.html" aria-label="Search">⌕</a><a class="icon-btn" href="notifications.html" aria-label="Notifications">♢<i class="badge"></i></a><a class="avatar" href="profile.html">${esc(initials)}</a></div></header><main class="page" id="pageContent"></main>${bottomNav()}<div class="toast" id="toast"></div><div id="modalRoot"></div><div class="app-bg"><i class="orb a"></i><i class="orb b"></i></div>`;
  bindInstallButtons();
}
function bottomNav(){ const items=[['home','⌂','Home'],['services','◫','Services'],['notifications','♢','Updates'],['profile','○','Profile'],['settings','⚙','Settings']]; return `<nav class="bottom-nav">${items.map(([id,icon,label])=>`<a class="nav-item ${page===id?'active':''}" href="${id}.html"><span>${icon}</span><span>${label}</span></a>`).join('')}</nav>`; }
function renderHome(){ const user=store.get('user',{name:'Dost'}); $('#pageContent').innerHTML=`<div class="ai-dashboard-hero"><div><span class="pill">TODO AI • GEMINI POWERED</span><h1>Namaste, ${esc(user.name.split(' ')[0])}.<br><span>How can I help?</span></h1><p>Premium AI workspace for chat, study, writing, ideas, translation aur Lagma website help.</p><div class="dashboard-actions"><a class="btn btn-primary" href="service-detail.html?id=chat">Start AI Chat</a><button class="btn btn-soft install-app-action" type="button">Install TODO AI</button><a class="btn btn-soft" href="../">Lagma Website</a></div></div><div class="ai-orb-card"><span>T</span><strong>TODO AI</strong><small>Installable AI app</small></div></div><section class="install-card"><div><span class="install-badge">PWA READY</span><h2>TODO AI ko phone me app ki tarah install karein</h2><p>Home screen se one-tap open, fullscreen experience aur fast cached loading.</p></div><button class="btn btn-primary install-app-action" type="button">Install App</button></section><form class="search premium-search" action="search.html"><span>⌕</span><input name="q" placeholder="Ask or search tools..."></form><div class="section-head"><h2>AI Tools</h2><a href="services.html">View all</a></div><div class="grid grid-4 premium-tools">${services.slice(0,4).map(serviceCard).join('')}</div><div class="section-head"><h2>Latest updates</h2><a href="notifications.html">See all</a></div><div class="list premium-list">${notices.slice(0,2).map(noticeItem).join('')}</div>`; bindInstallButtons(); }
function renderServices(){ $('#pageContent').innerHTML=`${pageHead('All Services','Powerful AI tools, ek hi jagah.')}<form class="search" id="serviceSearch"><span>⌕</span><input placeholder="Service search karein..."></form><div class="grid grid-3" id="serviceGrid" style="margin-top:20px">${services.map(serviceCard).join('')}</div>`; $('#serviceSearch').onsubmit=e=>e.preventDefault(); $('#serviceSearch input').oninput=e=>filterServices(e.target.value); }
function filterServices(q){ const filtered=services.filter(s=>(s.title+s.desc).toLowerCase().includes(q.toLowerCase())); $('#serviceGrid').innerHTML=filtered.length?filtered.map(serviceCard).join(''):emptyState('⌕','No result found','Kisi doosre keyword se search karein.'); }
function serviceCard(s){return `<a class="card clickable" href="service-detail.html?id=${s.id}"><div class="feature-icon">${s.icon}</div><h3>${s.title}</h3><p>${s.desc}</p>${s.coming?'<span class="coming">COMING SOON</span>':''}</a>`}
function renderDetail(){ const id=new URLSearchParams(location.search).get('id')||'chat',s=services.find(x=>x.id===id); document.body.classList.toggle('chat-premium-page',id==='chat'); if(!s){render404();return} const saved=store.get('saved',[]).includes(id); $('#pageContent').innerHTML=id==='chat'?chatMarkup():`<a class="back" href="services.html">← Back to services</a><section class="detail-hero"><div class="feature-icon">${s.icon}</div><div><h1>${s.title}</h1><p>${s.desc}</p><div class="detail-actions"><button class="btn btn-soft" id="saveBtn">${saved?'★ Saved':'☆ Save'}</button><button class="btn btn-soft" id="shareBtn">↗ Share</button></div></div></section>${s.coming?emptyState('◷','Coming Soon','Yeh feature development mein hai. Update ke liye notifications check karein.'):toolMarkup(s)}`; bindInstallButtons(); if(id!=='chat'){ $('#saveBtn').onclick=()=>toggleSave(id);$('#shareBtn').onclick=()=>shareService(s); } if(!s.coming&&id==='chat')initChat(); if(!s.coming&&id!=='chat')initTool(s); }
function toolMarkup(s){return `<section class="content-card"><h2>${s.title} kaise use karein?</h2><p>${s.info}</p><form id="toolForm"><div class="form-group"><label>Apni requirement likhein</label><div class="field"><textarea id="toolPrompt" placeholder="Example: Professional leave email likho..."></textarea></div><small class="error" data-error="toolPrompt"></small></div><button class="btn btn-primary" id="toolBtn">✦ Generate with AI</button></form><div id="toolResult"></div></section>`}
function initTool(s){$('#toolForm').onsubmit=async e=>{e.preventDefault();const prompt=$('#toolPrompt').value.trim();if(!prompt){setError('toolPrompt','Requirement likhna zaroori hai');return}const btn=$('#toolBtn');loading(btn,true,'Generating...');const result=$('#toolResult');try{const reply=await askAI(`${s.title} task: ${prompt}`);result.innerHTML=`<div class="content-card"><h2>Result</h2><p style="white-space:pre-wrap">${esc(reply)}</p></div>`}catch(err){showToast(err.message)}finally{loading(btn,false,'✦ Generate with AI')}}}
function chatMarkup(){return `<section class="ai-chat-shell"><header class="ai-chat-top"><a class="ai-menu-dot" href="../" aria-label="Back to Lagma">‹</a><div class="ai-model-title"><strong>TODO AI</strong><button type="button">Gemini Flash⌄</button></div><div class="ai-chat-actions"><button class="install-app-action icon-only" type="button" aria-label="Install TODO AI">⇩</button><a href="home.html" aria-label="Dashboard">⌂</a><a href="services.html" aria-label="Tools">⋯</a></div></header><div class="chat-messages ai-chat-messages" id="chatMessages"><div class="ai-empty-state"><div class="ai-face">T</div><h1>Namaste! Main TODO AI hoon.</h1><p>Duniya ka koi bhi sawaal, study, writing, ideas ya Lagma website — jo chahiye poochhiye.</p><button class="btn btn-primary install-app-action" type="button">Install TODO AI</button></div></div><form class="chat-form ai-composer" id="chatForm"><button class="composer-plus" type="button" aria-label="Add">+</button><input id="chatInput" maxlength="6000" placeholder="Ask anything" required><button class="composer-mic" type="button" aria-label="Voice">⌁</button><button class="composer-send" id="chatBtn" aria-label="Send">↑</button></form></section>`}
function initChat(){let history=[];$('#chatForm').onsubmit=async e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;addChat('user',text);history.push({role:'user',text});input.value='';const btn=$('#chatBtn');loading(btn,true,'…');const thinking=addThinking();try{const reply=await askAI(null,history);history.push({role:'assistant',text:reply});thinking.remove();addChat('assistant',reply)}catch(err){thinking.remove();addChat('assistant',`⚠ ${err.message}`)}finally{loading(btn,false,'↑');input.focus()}}}
async function askAI(prompt,history){const messages=history||[{role:'user',text:prompt}];const res=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages})});const data=await res.json();if(!res.ok)throw new Error(data.error||'AI response nahi mila.');return data.reply}
function addThinking(){const box=$('#chatMessages');box.querySelector('.ai-empty-state')?.remove();const row=document.createElement('div');row.className='chat-row thinking-row';row.innerHTML='<div class="thinking-dots"><i></i><i></i><i></i></div><span>Refining the response</span>';box.append(row);keepChatVisible(row,'thinking');return row}
function addChat(role,text){const box=$('#chatMessages');box.querySelector('.ai-empty-state')?.remove();const row=document.createElement('div');row.className=`chat-row ${role==='user'?'user':'assistant'}`;const bubble=document.createElement('div');bubble.className='chat-bubble';bubble.textContent=text;row.append(bubble);if(role==='assistant'){const actions=document.createElement('div');actions.className='chat-response-actions';actions.innerHTML='<button type="button" aria-label="Good">♡</button><button type="button" aria-label="Retry">↻</button><button type="button" aria-label="Copy">⧉</button><button type="button" aria-label="More">•••</button><small>TODO AI can make mistakes.</small>';actions.querySelector('[aria-label="Copy"]').onclick=()=>navigator.clipboard?.writeText(text).then(()=>showToast('Response copied'));row.append(actions)}box.append(row);keepChatVisible(row,role)}
function keepChatVisible(row,role){requestAnimationFrame(()=>{if(role==='assistant'){row.scrollIntoView({block:'start',behavior:'smooth'});return}row.scrollIntoView({block:'end',behavior:'smooth'})})}
function toggleSave(id){let saved=store.get('saved',[]);saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];store.set('saved',saved);$('#saveBtn').textContent=saved.includes(id)?'★ Saved':'☆ Save';showToast(saved.includes(id)?'Saved successfully':'Removed from saved')}
async function shareService(s){const data={title:`TODO AI — ${s.title}`,text:s.desc,url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);showToast('Link copied')}}catch{} }
function renderSearch(){const q=new URLSearchParams(location.search).get('q')||'';$('#pageContent').innerHTML=`${pageHead('Search','Services aur updates turant dhoondhein.')}<form class="search" id="globalSearch"><span>⌕</span><input id="searchInput" value="${esc(q)}" placeholder="Search TODO AI..."></form><div id="searchResults" style="margin-top:20px"></div>`;$('#globalSearch').onsubmit=e=>e.preventDefault();$('#searchInput').oninput=e=>showSearch(e.target.value);showSearch(q)}
function showSearch(q){const box=$('#searchResults');if(!q.trim()){box.innerHTML=emptyState('⌕','Search anything','Service, feature ya notification ka naam likhein.');return}const sq=q.toLowerCase(),ss=services.filter(s=>(s.title+s.desc).toLowerCase().includes(sq)),nn=notices.filter(n=>(n.title+n.text).toLowerCase().includes(sq));const results=[...ss.map(s=>`<a class="list-item" href="service-detail.html?id=${s.id}"><div class="feature-icon">${s.icon}</div><div class="list-copy"><h3>${s.title}</h3><p>${s.desc}</p></div>→</a>`),...nn.map(noticeItem)];box.innerHTML=results.length?`<div class="list">${results.join('')}</div>`:emptyState('∅','No result found','Spelling check karke dobara try karein.')}
function renderNotifications(){const read=store.get('readNotices',[]);$('#pageContent').innerHTML=`${pageHead('Notifications','Latest updates aur important information.','<div><button class="btn btn-soft" id="readAll">Mark all read</button> <button class="btn btn-soft" id="clearAll">Clear all</button></div>')}<div class="list" id="noticeList">${notices.map(n=>noticeItem({...n,unread:n.unread&&!read.includes(n.id)})).join('')}</div>`;$('#readAll').onclick=()=>{store.set('readNotices',notices.map(n=>n.id));renderNotifications();showToast('All marked as read')};$('#clearAll').onclick=()=>{$('#noticeList').innerHTML=emptyState('♢','No notifications','Nayi update aane par yahan dikhegi.');showToast('Notifications cleared')};document.querySelectorAll('[data-notice]').forEach(x=>x.onclick=()=>openNotice(Number(x.dataset.notice)))}
function noticeItem(n){return `<article class="list-item ${n.unread?'unread':''}" data-notice="${n.id}"><div class="feature-icon">♢</div><div class="list-copy"><h3>${n.title}</h3><p>${n.text}</p></div><time>${n.date}</time></article>`}
function openNotice(id){const n=notices.find(x=>x.id===id);let read=store.get('readNotices',[]);store.set('readNotices',[...new Set([...read,id])]);showModal(n.title,`<p>${n.text}</p><small>${n.date}</small>`)}
function renderProfile(){const user=store.get('user',{name:'Guest',email:'',phone:''}),saved=store.get('saved',[]);$('#pageContent').innerHTML=`${pageHead('My Space','Bina account ke aapki local activity aur saved tools.')}<div class="grid grid-2 profile-layout"><section class="card profile-card"><div class="avatar">${esc(initials(user.name))}</div><h2>${esc(user.name)}</h2><p>Login ki zaroorat nahi—seedha TODO AI use karein.</p><button class="btn btn-primary" id="editProfile" style="margin-top:20px">Naam badlein</button></section><section class="card"><div class="menu"><div class="menu-row"><span>◷</span><strong>My Activity</strong><small>${store.get('activity',0)} actions</small></div><div class="menu-row" id="savedItems"><span>☆</span><strong>Saved Items</strong><small>${saved.length} saved</small></div><a class="menu-row" href="help.html"><span>?</span><strong>Help & Support</strong><b>›</b></a></div></section></div>`;$('#editProfile').onclick=()=>editProfile(user);$('#savedItems').onclick=()=>showSaved(saved)}
function editProfile(user){showModal('Edit Profile',`<form id="editForm"><div class="form-group"><label>Full Name</label><div class="field"><input id="editName" value="${esc(user.name)}"></div></div><div class="form-group"><label>Phone</label><div class="field"><input id="editPhone" value="${esc(user.phone||'')}" maxlength="10"></div></div><button class="btn btn-primary btn-block">Save Changes</button></form>`);$('#editForm').onsubmit=e=>{e.preventDefault();const name=$('#editName').value.trim(),phone=$('#editPhone').value.trim();if(name.length<2||phone&&!/^\d{10}$/.test(phone)){showToast('Valid name aur phone likhein');return}store.set('user',{...user,name,phone});closeModal();renderProfile();renderShell();renderProfile();showToast('Profile updated')}}
function showSaved(ids){const items=services.filter(s=>ids.includes(s.id));showModal('Saved Items',items.length?`<div class="list">${items.map(s=>`<a class="list-item" href="service-detail.html?id=${s.id}"><div class="feature-icon">${s.icon}</div><strong>${s.title}</strong></a>`).join('')}</div>`:emptyState('☆','No saved items','Service par Save button tap karein.'))}
function confirmLogout(){showModal('Logout karein?',`<p>Kya aap apne account se logout karna chahte hain?</p><div class="modal-actions"><button class="btn btn-soft" onclick="closeModal()">Cancel</button><button class="btn btn-danger" id="confirmLogout">Logout</button></div>`);$('#confirmLogout').onclick=()=>{localStorage.removeItem('todo_user');location.href='login.html'}}
function renderSettings(){const settings=store.get('settings',{theme:'light',language:'Hindi',notifications:true});$('#pageContent').innerHTML=`${pageHead('Settings','TODO AI ko apne hisaab se customize karein.')}<section class="card"><div class="menu"><div class="menu-row"><span>◐</span><strong>Dark Mode</strong><label class="switch"><input id="themeToggle" type="checkbox" ${settings.theme==='dark'?'checked':''}><i></i></label></div><div class="menu-row"><span>文</span><strong>Language</strong><select id="language" class="btn btn-soft"><option>Hindi</option><option>English</option><option>Hinglish</option></select></div><div class="menu-row"><span>♢</span><strong>Notifications</strong><label class="switch"><input id="notifyToggle" type="checkbox" ${settings.notifications?'checked':''}><i></i></label></div><a class="menu-row" href="privacy.html"><span>⌾</span><strong>Privacy Policy</strong><b>›</b></a><a class="menu-row" href="terms.html"><span>▤</span><strong>Terms & Conditions</strong><b>›</b></a><a class="menu-row" href="about.html"><span>ⓘ</span><strong>About App</strong><b>›</b></a><a class="menu-row" href="help.html"><span>✉</span><strong>Contact Support</strong><b>›</b></a></div></section>`;$('#language').value=settings.language;$('#themeToggle').onchange=e=>saveSetting('theme',e.target.checked?'dark':'light');$('#language').onchange=e=>saveSetting('language',e.target.value);$('#notifyToggle').onchange=e=>saveSetting('notifications',e.target.checked)}
function saveSetting(key,value){const s=store.get('settings',{});s[key]=value;store.set('settings',s);if(key==='theme')applyTheme();showToast('Setting saved')}
function applyTheme(){const s=store.get('settings',{theme:'light'});document.documentElement.dataset.theme=s.theme||'light';document.querySelector('meta[name=theme-color]')?.setAttribute('content',s.theme==='dark'?'#090b18':'#6c5ce7')}
function renderHelp(){const user=store.get('user',{});$('#pageContent').innerHTML=`${pageHead('Help & Support','Sawaal ho to hum yahan hain.')}<div class="grid grid-2"><section><div class="section-head"><h2>Frequently asked questions</h2></div><div class="faq"><details><summary>TODO AI free hai?</summary><p>Gemini free-tier limits ke andar usage free hai. Limits provider ke rules par depend karti hain.</p></details><details><summary>Mera data kahan save hota hai?</summary><p>Demo profile aur settings isi browser ke local storage mein save hote hain.</p></details><details><summary>AI galat jawab de sakta hai?</summary><p>Haan. Medical, legal aur financial information hamesha trusted source se verify karein.</p></details></div><div class="support-actions"><a class="btn btn-soft" href="mailto:support@example.com">✉ Email</a><a class="btn btn-soft" href="tel:+910000000000">☎ Call</a></div></section><section class="card"><h2>Contact us</h2><form id="supportForm"><div class="form-group"><label>Name</label><div class="field"><input id="supportName" value="${esc(user.name||'')}"></div></div><div class="form-group"><label>Email / Phone</label><div class="field"><input id="supportContact" value="${esc(user.email||user.phone||'')}"></div></div><div class="form-group"><label>Message</label><div class="field"><textarea id="supportMessage"></textarea></div></div><button class="btn btn-primary btn-block" id="supportBtn">Submit Request</button></form></section></div>`;$('#supportForm').onsubmit=e=>{e.preventDefault();if($('#supportName').value.trim().length<2||!validIdentity($('#supportContact').value.trim())||$('#supportMessage').value.trim().length<10){showToast('Sabhi fields sahi se bharein');return}loading($('#supportBtn'),true,'Submitting...');setTimeout(()=>{showToast('Support request submitted successfully');$('#supportForm').reset();loading($('#supportBtn'),false,'Submit Request')},700)}}
function renderAbout(){ $('#pageContent').innerHTML=`<a class="back" href="settings.html">← Back</a>${pageHead('About TODO AI','Aapka smart, simple aur bilingual AI workspace.')}<section class="detail-hero"><div class="feature-icon">T</div><div><h1>TODO AI</h1><p>Think. Ask. Create.</p><span class="coming">VERSION 1.0.0</span></div></section><section class="content-card policy"><h2>Our purpose</h2><p>TODO AI ka purpose powerful artificial intelligence ko Hindi aur English users ke liye simple aur useful banana hai.</p><h2>Main features</h2><p>AI chat, writing assistance, study help, idea generation, translation, resume support aur personalized settings.</p><h2>Developer</h2><p>TODO AI ko Saksham Jha ne banaya hai. Yeh Lagma Village website ke visitors ko website information aur AI help dene ke liye Gemini technology se powered hai.</p></section>` }
function renderPolicy(type){const privacy=type==='privacy';$('#pageContent').innerHTML=`<a class="back" href="settings.html">← Back to settings</a><article class="content-card policy"><div class="page-title"><h1>${privacy?'Privacy Policy':'Terms & Conditions'}</h1><p>Last updated: 7 July 2026</p></div>${privacy?`<h2>Information we store</h2><p>This demo stores profile preferences, saved items and settings locally in your browser. AI messages are sent to the configured Gemini API for generating responses.</p><h2>Security</h2><p>Passwords are not stored by this demo. Never share passwords, OTPs, banking details or sensitive personal data in AI chat.</p><h2>Your choices</h2><p>You may clear browser storage or logout at any time. Production deployment should use a secure authentication provider and database security rules.</p>`:`<h2>Acceptable use</h2><p>Use TODO AI lawfully and responsibly. Do not use the service to harm people, bypass security or create illegal content.</p><h2>AI limitations</h2><p>AI responses may be incomplete or incorrect. Verify important medical, legal, financial and safety-related information.</p><h2>Availability</h2><p>Service availability depends on internet access and third-party API limits. Features may change as the app improves.</p>`}</article>`}
function render404(){if(!$('#pageContent'))return;$('#pageContent').innerHTML=emptyState('404','Page not found','Yeh page available nahi hai.',`<a class="btn btn-primary" href="home.html">Go to Home</a>`)}

function pageHead(title,subtitle,action=''){return `<div class="page-head"><div class="page-title"><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function emptyState(icon,title,text,action=''){return `<div class="empty"><div class="empty-icon">${icon}</div><h2>${title}</h2><p>${text}</p>${action}</div>`}
function initials(name){return name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}
function esc(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function loading(btn,on,text){btn.disabled=on;btn.textContent=text}
function showToast(msg){let toast=$('#toast');if(!toast){toast=document.createElement('div');toast.id='toast';toast.className='toast';document.body.append(toast)}toast.textContent=msg;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2500)}
function showModal(title,body){$('#modalRoot').innerHTML=`<div class="modal-wrap" id="modalWrap"><div class="modal"><div class="page-head"><h2>${title}</h2><button class="icon-btn" onclick="closeModal()">×</button></div>${body}</div></div>`}
window.closeModal=()=>{$('#modalRoot').innerHTML=''};
function isStandalone(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
function bindInstallButtons(){document.querySelectorAll('.install-app-action').forEach(btn=>{btn.onclick=installTodoApp});updateInstallButtons()}
function updateInstallButtons(){document.querySelectorAll('.install-app-action').forEach(btn=>{if(isStandalone()||store.get('installed',false)){btn.classList.add('is-installed');btn.textContent=(btn.classList.contains('icon-btn')||btn.classList.contains('icon-only'))?'✓':'Installed';btn.disabled=true}else{btn.disabled=false}})}
async function installTodoApp(){
  if(isStandalone()){showToast('TODO AI already installed hai');return}
  if(todoInstallPrompt){
    const prompt=todoInstallPrompt;
    todoInstallPrompt=null;
    prompt.prompt();
    const result=await prompt.userChoice.catch(()=>({outcome:'dismissed'}));
    showToast(result.outcome==='accepted'?'Installing TODO AI...':'Install cancel ho gaya');
    updateInstallButtons();
    return;
  }
  showModal('Install TODO AI',`<div class="install-guide"><p>Agar install popup nahi dikh raha, browser menu se install karein:</p><ol><li>Chrome/Edge me top-right <strong>⋮</strong> menu kholein.</li><li><strong>Add to Home screen</strong> ya <strong>Install app</strong> choose karein.</li><li>TODO AI icon home screen par aa jayega.</li></ol><a class="btn btn-primary btn-block" href="./">Open TODO AI</a></div>`);
}
